### ISSUE TITLE
[Featured] 오늘의 한마디 기능

### ISSUE THREAD

**Issue by Yenowme** [innovationacademy-kr/slabs-saver#151]
외부필진이 오늘의 한마디를 입력하고, 편집장이 선정하는 기능 추가

- [x] 오늘의 한마디 데이터 테이블 추가
- [x] 오늘의 한마디 작성페이지 수정
- [x] 오늘의 한마디 관리 페이지 추가
  - [ ] 오늘의 한마디 과거날짜 비활성화
  - [ ] 오늘의 한마디 날짜 중복 막기

**Comment by kenu** [comment]
@Jung-Saver 
자료가 필요합니다.

**Comment by kenu** [comment]
[hello.txt](https://github.com/innovationacademy-kr/slaps-saver/files/6745190/hello.txt)

**Comment by Jung-Saver** [comment]
[7월 1일 회의 자료.pptx](https://github.com/innovationacademy-kr/slaps-saver/files/6745192/7.1.pptx)
[이메일 테블릿형태.pptx](https://github.com/innovationacademy-kr/slaps-saver/files/6745195/default.pptx)

**Comment by Jung-Saver** [comment]
[편집장 편집창_210702.pptx](https://github.com/innovationacademy-kr/slabs-saver/files/6752303/_210702.pptx)
수정한 페이지안 첨부했습니다.
