### ISSUE TITLE
[Feature request]인사동 유물 발견

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#173]
## 내용
서울 인사동에서 570년 전 금속활자 1,600점이 발견되다.  

SNS 공유
 
29일 오전 서울 종로구 국립고궁박물관 본관 강당에서 열린 서울 공평동 유적 출토 중요유물 언론공개회에서 조선 전기 금속활자 등이 공개되고 있다. [뉴스1]
 
서울 인사동 땅 속에서 조선 전기 때로 추정되는 1600여점 (한자 1,000점/ 한글 600점)의 금속활자가 쏟아져 나왔다. 지금까지 인쇄본으로만 전해지던 초창기 훈민정음 음운이 활자 실물로 나타난 것이다. 이는 그간 베일에 싸여있던 조선 전기 활자/인쇄 연구를 급진전시킬 역대급 유물로 평가 된다. 
 
왜 중요한가.
-	지금까지 전해진 활자 가운데 가장 이른 시기의 한글 금속활자가 다수 나왔다. 훈민정음 창제 당시 동국정운식 한자표기도 포함하고 있으며, 활자 크기가 대자(大字), 중자(中字), 소자, 특소자까지 다양.
-	한문 금속활자 중 일부는 세종 때 만들어진 금속활자 중 가장 완전한 형태로 칭송받는 ‘갑인자(甲寅字)’로 추정. 1434년 만들어진 ‘초주갑인자’일 경우, 가장 이른 시기의 조선 금속활자로 쿠텐베르크(1440년) 이전 금속활자 인쇄본을 가진 우리나라가 확실한 실물 활자까지 갖게 되는 것.  
조선 전기 금속활자가 그렇게 희귀한가.
-	현재 중박 및 규장각 등에 보관된 수십만자의 금속활자는 대부분 17‧18세기 이후 주조된 것들
-	조선 전기(임진왜란 이전) 금속활자는 중박 소장 을해자 한글활자 뿐이었다. 그런데 이번엔 을해자 한자도 나오고 한글도 훨씬 많이 나왔으며 을유자(1465년) 한자활자도 나옴. 

다른 유물은
-	물시계 부속품으로 추정되는 동제품, 천문시계 부품, 조선시대 화포인 총통(銃筒), 동종(銅鐘) 등 모두 금속 유물
-	기록으로만 전해온 조선시대 자동 물시계의 주전과 천문시계 실체가 처음 확인되어, 기록으로만 전해져오던 세종 시기 과학기술의 실체를 엿볼 수 있게 됨
 
왜 이곳에서 발견되었나
-	금속활자나 다른 유물들이 궁궐, 왕실이 아닌 시전과 중인들인 거주하던 건물에서 출토
-	모든 유물을 일부러 조각내고 잘라 넣어 사실상 ‘재화 재활용’으로 남긴 것으로 추청

**Comment by kenu** [comment]
![art_16249355712326_38fb91](https://user-images.githubusercontent.com/718691/124059278-cc5b0000-da65-11eb-8f0b-19d82d62b75e.jpeg)
