### ISSUE TITLE
[Feature request] 오늘의 기사 기능

### ISSUE THREAD

**Issue by padawanR0k** [innovationacademy-kr/slabs-saver#183]
## 내용
기사가 작성한 기사를 편집장이 선정하는 기능 추가

- [x] 오늘의 기사 데이터 테이블 추가
- [x] 메인페이지에서 오늘의 기사 조회
- [x] 오늘의 기사 관리 페이지 추가

**Comment by padawanR0k** [comment]
@Jung-Saver 안녕하세요 김정선님
현재 오늘의 기사를 선택할 수 있는 화면을 개발하려고합니다. 
![image](https://user-images.githubusercontent.com/35283339/124584754-92d42b80-de8f-11eb-9674-e05b18c24737.png)
전달받았던 기획서에서 오늘의 한마디를 선택하는 기능을 처럼 
아예 따로 페이지를 분리해서 오늘의 기사를 선택하는 페이지를 만드려고합니다.

그런데 이때 오늘의 기사로 선택할 수 있는 기사들은 어떤 상태여야하는지 잘 모르겠어서 질문드립니다.
1. 임시작성, 작성완료, 출고, 게재 중 어떤 상태의 기사들이 오늘의 기사로 선택될수 있는 기사인가요?

**Comment by Jung-Saver** [comment]
유록님
 
안녕하세요? 문의 주신 사항에 답변드립니다.
 
오늘의 한마디는 외부필진이나 편집장이 작성합니다.
 
'출고'상태의 글을 '게재'시키는 작업임으로 '출고'상태가 맞습니다. 
 
감사합니다.
 
김정선 드림
 
 
 


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by Jung-Saver** [comment]
유록님

문의 주신건은 '오늘의 기사'네요..ㅠㅠ
오늘의 기사는 게재 상태입니다. 

감사합니다.
