### ISSUE TITLE
[Bug report] 메인 화면에서 기사가 확장된 형태로 보임

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#187]
## 발생 일시
2021년 7월 5일
## 발생 위치
메인화면
## 증상
  1. 메인화면에서 기사가 확장된 형태로 보임 
  2. 100자 + 1단락만 보인 후, 더 자세히 버튼 클릭 시 확장 되어야 함.
  3.  확장 시, 더 보기 버튼은 보이지 않아야 함.

**Comment by padawanR0k** [comment]
1,2
![image](https://user-images.githubusercontent.com/35283339/124435549-11f23280-ddb0-11eb-808a-1266856db826.png)
기사 작성시 들여쓰기문법을 맞출 경우에만 해당 부분이 적용됩니다. 첫번째 들여쓰기 후 Tab 버튼을 눌러 2번쩨 depth로 들여쓰기하셔야합니다.
- 1
  - 2



3. 해당 부분은 적용하겠습니다.

**Comment by Jung-Saver** [comment]
유록님,
설명해주신 방법이 사용자마다 익히기에 혼선이 있을 거 같습니다. 
그래서 다음과 같이 정리하면 어떨까 합니다.

1, 100자 브리핑 섹션만 확장 전에 노출 되도록한다. 
(작성자가 100자 브리핑 외 노출하고 싶은 컨텐츠는 
100자 브리핑 섹션 안에 작성한다)

2. 소단락에 내용은 모두 더 자세히 버튼 클릭 후 보여진다

**Comment by padawanR0k** [comment]
네 좋은거같습니다! 해당 내용으로 반영하겠습니다
