### ISSUE TITLE
[Bug report] 기사 임시저장 및 출고 오류

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#189]
## 발생 일시
 7월 ~7,8일

## 발생 위치
편집장 로그인 후 기사 작성

## 증상
기사 임시저장 클릭시 실패 알림

## 스크린샷
![화면 캡처 2021-07-08 114257](https://user-images.githubusercontent.com/84112402/124854278-143bd300-dfe2-11eb-87d7-7ddf9217ebaf.jpg)

**Comment by Jung-Saver** [comment]
![화면 캡처 2021-07-08 114257](https://user-images.githubusercontent.com/84112402/124854223-025a3000-dfe2-11eb-83c9-cce61b2757e8.jpg)
이 사진입니다

**Comment by Yenowme** [comment]
에러 확인 감사합니다! 
혹시 해당 에러가 발생한 웹페이지 url과 기사 내용을 같이 올려주실 수 있을까요?
버그를 잡는데 해당 내용이 필요합니다. 감사합니다

**Comment by Jung-Saver** [comment]
https://saver.42seoul.io/author/articles/new 
 
기사내용
 
창기트윈스, LG트윈스 대체불가의 리드오프- 홍창기
홍창기가 끝내기 홈런을 치고 환호하고 있다.  일간스포츠
2020년 혜성처럼 LG트윈스에 나타난 홍창기가 풀타임 주전 첫 해인 이번 시즌에도 팀의 리드오프로서 해결사 역할을 해내고 있다.
 

2021년 성적
- 7월 6일 현재 75경기, 타율 0.338 3홈런 32타점 58득점 13도루 OPS(출루율+장타율) 0.914을 기록 중.
- 실제로 올 시즌 규정 타석을 소화한 LG 타자 중 가장 높은 출루율(0.475)을 기록. LG 내 유일한 4할 대 출루율 보유자다. 장타율도 4할대(0.439)로 팀 내 4위
 
리드오프의 역할
-      1번 타자 리드오프는 득점의 기회를 만드는 역할
-     홍창기는 높은 출루율로 KBO 10 개 구단 가운데 타격지표가 가장 나쁜 LG 트윈스의 타선이 꽉 막혔을 땐 혈을 뚫어주는 선수 역할을 하고 있음.
-      리드오프로 나서 기회를 창출하거나 해결사 역할까지 하면서 경기 흐름을 바꿔놓는 ‘게임 체인져’ 역할
 
대체불가의 선수
-      도쿄 올림픽 엔트리에 포함되지 않아 태극마크를 달고 국위선양할 기회는 놓쳤지만, 홍창기는 리그에서 맹활약하며 자신의 가치를 드높이고 있음
-      LG트윈스 류지현 감독: "홍창기라는 유형의 선수는 우리팀의 소중한 자산"이라면서 "기존 선수 외 홍창기나 문보경 등 타석에서 끈질기게 싸움하는 선수가 더 생긴다면 훨씬 탄탄한 타선 완성될 것"이라고 말했다. 
 


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by padawanR0k** [comment]
@Jung-Saver 
안녕하세요:) 
thesaver.io에 이슈해결후 업데이트 완료되었습니다.
