### ISSUE TITLE
[Bug report] 서체, 자간격, 행간격 등 고정 안됨

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#203]
## 
![스샷_0713](https://user-images.githubusercontent.com/84112402/125380284-eb924f80-e3cc-11eb-96de-001206d598bc.jpg)

**Comment by padawanR0k** [comment]
안녕하세요 :)
혹시 해당 기사를 외부에서 복사 붙이기하신 경우인가요? 
해당 페이지에서 태그를 그대로 긁어 오게되어 해당 화면처럼 깨져 보일 수 있습니다.
![image](https://user-images.githubusercontent.com/35283339/125381277-95261080-e3ce-11eb-8bc1-fda4612f46cd.png)

**Comment by Jung-Saver** [comment]
현재 작성해놓은 기사를 복사 붙여넣기를 하고 있습니다. 
이전에도 같은 방식으로 진행해도 문제가가 발생하지 않았는데
복붙하면 같은 문제가 발생할까요?

**Comment by padawanR0k** [comment]
네 사용한 툴이 달라져서, 이제 복붙하게 된다면 동일한 문제가 계속 발생할거같습니다.

**Comment by Jung-Saver** [comment]
![오늘자](https://user-images.githubusercontent.com/84112402/125383518-7c1f5e80-e3d2-11eb-8471-f15470284891.jpg)
![스샷 0713](https://user-images.githubusercontent.com/84112402/125383538-82add600-e3d2-11eb-960b-68b09af7c57f.jpg)

툴 안에서 작성해도 동일한 문제가 발생하는 거 같습니다.

**Comment by padawanR0k** [comment]
![image](https://user-images.githubusercontent.com/35283339/125385365-4f207b00-e3d5-11eb-9b4c-9c09d3277003.png)
"내년 최저... " 이 부분에 맑은고딕이라는 폰트가 들어가있는데, 툴 밖에서 복사해온 문자일 경우 다음과 같이 됩니다.
일단 복사해와도 최대한 스타일을 벗겨내는 방향으로 기능을 수정하겠습니다.

**Comment by Jung-Saver** [comment]
![스샷0714](https://user-images.githubusercontent.com/84112402/125588409-e7faacff-95ad-4381-a662-f2cb49704953.jpg)
![KakaoTalk_20210714_171812560_01](https://user-images.githubusercontent.com/84112402/125588521-c305804d-b411-4df8-9623-11117977b25b.jpg)

cms에 등록시 단락 들여쓰기에 앞에 기호 넣었는데
모바일 상에는 기호 없음.
