### ISSUE TITLE
[Bug report] 영상삽입 시 사이즈 조정

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#206]
## 단락 내 영상 삽입 시, 단락 내로 사이즈 조정이 안됨
![KakaoTalk_20210714_171812560_02](https://user-images.githubusercontent.com/84112402/125588794-c8c11ea7-f6a4-46a1-8086-c7839e55793f.jpg)

**Comment by parkjh2568** [comment]
안녕하세요 영상 사이즈 조절 관련해서 문의가 있습니다.
화면의 크기에 맞춰서 영상사이즈를 조절할것인데 
현재상황에서 영상의 세로길이는 고정한체 가로길이만 화면 사이즈에 맞게 조정할까요?
아니면 영상의 가로세로 비율고정한체 화면 사이즈가 바뀌면 같이 조정을 하게 할까요??

**Comment by Jung-Saver** [comment]
영상의 가로세로 비율을 고정한 채, 화면사이즈가 바뀌는 방향으로 부탁드립니다.

**Comment by parkjh2568** [comment]
밑에 두곳에 영상사이즈 작업을 적용해두었는데 
말씀하신것과 부합한지 확인한번 해주실수 있나요?

https://dev.thesaver.io/articles/detail/129
https://dev.thesaver.io/

**Comment by Jung-Saver** [comment]
적용해주신  시안 봤습니다. 요청사항이 잘 반영되었습니다. 
감사합니다.
