### ISSUE TITLE
[Feature request] 이전 기사(포스트) 링크

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#245]
## 기사 가운데 사건에 진행에 따라 앞선 기사와 연결될 필요가 있습니다.

예를 들어, 1차 기사 : 청해부대 확진자 발생
                 2차 기사 : 청해부대 전원 귀국을 위한 수송기 파견
                 3차 기사 : 청해부대 승조원 전원 귀국, 생활안전센터 입소

이 경우, 2-3차 기사에  중복보도를 피하기 위해 1,2차 기사가 링크될 경우가 발생합니다. 

이 기능도 검토 부탁드립니다.

**Comment by hokim2407** [comment]
현재 있는 에디터 링크 기능 말고 UI적으로 이전 기사와 연결되는 링크를  말씀하시는 건가요? 어떤 형태를 원하시는지 감이 잘 안잡혀서 디자인 예시가 있으면 좋을 것 같습니다.

**Comment by Jung-Saver** [comment]
예를 들면, 아래 1번 기사에  앞서 게재했던 2번 기사 링크를 넣는 것을 말합니다. 

1) BTS ‘버터’ 빌보드 핫100 7주 연속 1위 다음 주는?

2) BTS ‘버터’ 빌보드 핫100 6주 연속 1위 전설을 만들어 가는 중.

디자인적으로는 에디터에 있는 아웃링크하는 방식입니다.  감사합니다.

**Comment by hokim2407** [comment]
https://dev.thesaver.io/author 에 해당 기능이 업데이트 되었습니다.
![링크 검색](https://user-images.githubusercontent.com/67669579/129909844-a7c4b3dd-6d6f-48d1-8ec2-9f11354c065d.PNG)
헤드라인 검색을 통해 기사를 찾아서 클릭하면 소단락에 자동으로 링크삽입되도록 만들었습니다. 
말씀하신 기능이 맞는지 확인 부탁드립니다!

**Comment by Jung-Saver** [comment]
네 맞습니다. 감사합니다.

**Comment by hokim2407** [comment]
넵 확인 감사합니다~
