### ISSUE TITLE
[Feature request] 앱스토어 등록을 위한 아이콘

### ISSUE THREAD

**Issue by kenu** [innovationacademy-kr/slabs-saver#261]
## 내용
@Jung-Saver 님 애플 앱스토어와 구글 플레이스토어에 앱 등록을 위해서 필요한 아이콘 요청합니다.
참고: 
* https://play.google.com/store/apps/details?id=bbc.mobile.news.ww 
* https://apps.apple.com/us/app/bbc-news/id364147881
1024x1024 사이즈입니다.

천천히 앱스토어 등록시 설명과 스크린샷 등도 준비를 해야할 것 같습니다.
아이콘이 만들어지면 모바일웹에서의 favicon.ico 작업도 동시에 진행하겠습니다.
favicon: 브라우저 탭 좌측에 보이는 아이콘

**Comment by Jung-Saver** [comment]
디자이너분께 부탁드려놓겠습니다.

**Comment by Jung-Saver** [comment]
멘토님, 안드로이드와 ios 스크린샷 사이즈 등 규정 등을 알 수 있을까요?
디자이너분이 앱 등록을 오래전에 하셔서
새로운 규격이나 가이드가 있으면 알려주셨으면 합니다. 

감사합니다.

**Comment by kenu** [comment]
@Jung-Saver 
답신이 늦어서 미안합니다.
iOS 1024x1024
Android 512x512
입니다.

**Comment by Jung-Saver** [comment]
멘토님 디자인은 언제까지 준비되어야할까요?

**Comment by kenu** [comment]
목요일까지 준비되면 좋을 것 같습니다.

**Comment by Jung-Saver** [comment]
멘토님 디자이너님이 휴가로 인해 오늘까지 디자인 준비는 어렵습니다.
차주까지 작업해보겠습니다.

**Comment by kenu** [comment]
넵, 감사합니다.

**Comment by Jung-Saver** [comment]
![saver_app icon_1024](https://user-images.githubusercontent.com/84112402/128318866-51d3181c-e56d-4b3c-82fb-4ae718b33768.png)
![saver_app icon_512](https://user-images.githubusercontent.com/84112402/128318877-f6724e2b-973f-4aa5-ba45-95903f72a7c7.png)


앱아이콘 전달드립니다.

**Comment by kenu** [comment]
감사합니다.
