### ISSUE TITLE
[Bug report] 동일 단락에서 일부단어 Bold처리 시 오류

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#291]
![KakaoTalk_20210729_115012270](https://user-images.githubusercontent.com/84112402/127424050-f4265612-e6ce-4725-8ebb-27ae7c6b7de4.jpg)

볼드처리한 단어가 줄이 안맞고 내려감.

**Comment by hokim2407** [comment]
수정되었습니다.
