### ISSUE TITLE
[Feature request] am7, pm7 카테고리 팔로잉 관련 @thesaver @Jung-Saver

### ISSUE THREAD

**Issue by kyu-baek** [innovationacademy-kr/slabs-saver#363]
## 내용
![image](https://user-images.githubusercontent.com/69143394/128817323-f423a98e-b051-41fe-bf5a-10c308d6df8b.png)

현재 알림 기능은, 새로운 기사가 게재된 상태에서 알림 보내기 버튼을 통해 
푸시 알림과, 알림 페이지 리스트에 올라오는 기사들을 제어하고 있습니다. 

am7, pm7 을 팔로잉 한 경우와 팔로잉 하지 않았을 경우, 
알림 리스트 페이지와, 푸시 알림 에서 어떤 차이가 발생하는 지 여쭈어보고 싶습니다.

**Comment by Jung-Saver** [comment]
![am7](https://user-images.githubusercontent.com/84112402/129143285-3a57cc46-2a77-4be8-8f7a-b2cc9208f001.jpg)
![pm7](https://user-images.githubusercontent.com/84112402/129143298-efa1b47c-404d-40de-84db-0904c5b1f532.jpg)

am7, pm7은 위와 같은 형태의 기사가 매일 오전 7시, 오후7시에 자동으로 피드 됩니다.  
알림, 푸시는 언급하신 기사와 동일하게 처리해주시면 됩니다.

**Comment by jis-kim** [comment]
@Jung-Saver 안녕하세요. am7, pm7에 포함되는 기사에 대해 시간 기준이 있는지 문의 드리고 싶습니다.
예를 들어 am7에 포함되는 기사가 am7 체크된 기사 중 그 전 날 오후 7시 이후부터 당일 오전 6:59분까지 출고된 기사들만인지, 
아니면 출고된 시간과 상관없이 am7에 체크 되어있다면 매일 피드되는 am7에 포함되는지, 다른 기준이 있는지 궁금합니다.

**Comment by Jung-Saver** [comment]
[7월 1일 회의 자료.pdf](https://github.com/innovationacademy-kr/slabs-saver/files/6973455/7.1.pdf)
이 자료료를 보시면 도움이 될 겁니다. 

감사합니다.

**Comment by kyu-baek** [comment]
답변 감사드립니다!
