### ISSUE TITLE
[Bug report] 기사 저장 및 출고 오류

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#371]
## 발생 일시
![image](https://user-images.githubusercontent.com/84112402/128970263-febbc491-c782-4512-a62e-51d2c86894b0.png)

**Comment by hokim2407** [comment]
저희측에서 테스트 해봤을 때 오류가 안나타나서 오류가 발생하셨을 당시의 계정 권한(기자/데스크/치프...)/헤드라인/사진 설명/사진 출처/100자 브리핑/소단락을 함께 첨부해주시면 좋을 것 같습니다. 그리고 F12를 누르셔서 consol 탭에 나타나는 에러 로그를 함께 적어주시면 에러 재현이 안되어도 원인을 알아보는데 큰 도움이 됩니다.
![콘솔](https://user-images.githubusercontent.com/67669579/129521859-156bd1f6-6389-4496-a628-99e6ac3b8c22.PNG)
 
그리고 오류 상황에서 새로고침을 했을때 로그인 페이지로 이동했는지 여부가 궁금합니다!

**Comment by Jung-Saver** [comment]
현재 해당 오류는 수정됐습니다. 
다음부터는 요청하신 사항까지 반영하도록 하겠습니다. 

감사합니다.
