### ISSUE TITLE
[Bug report] 카카오톡 javascript 키  수동설정

### ISSUE THREAD

**Issue by ejei0g** [innovationacademy-kr/slabs-saver#409]
## 발생 위치
- public/javascripts/sharetotal.js
## 증상
- 업데이트마다 카카오 앱키를 수동으로 설정해줘야 함.
- git pull 시 "카카오 앱키 추가"와 "kakao js key" conflict 로 인한 aws에서  직접수정필요
- 개인 실수로 javascript 키와 네이티브앱키로 잘못설정시 링크미적용
- config파일을 통한 접근 필요

**Comment by kenu** [comment]
.env 파일로 옮겨야 할 것 같네요. `process.env.KAKAO_KEY`

**Comment by ejei0g** [comment]
클라이언트 상에서 환경변수값을 볼 수 있음
카카오 앱키 뿐만아니라 author페이지에서도 AWS관련 환경변수 값을 볼 수 있음
