### ISSUE TITLE
[Feature request] iOS 앱스토어 등록을 위한 정보 요청

### ISSUE THREAD

**Issue by ejei0g** [innovationacademy-kr/slabs-saver#415]
안녕하세요! iOS 앱스토어 등록중인데 필요한 정보 요청드립니다.

### 스크린샷 및 미리보기 제출
![image](https://user-images.githubusercontent.com/20364535/129551159-8f62358b-d80b-4715-8266-f3415c01cee3.png)

- 앱 스크린샷 이미지 최소 2장 최대 10장
  -  iPhone 6.5형 (2778 * 1284)
  -  iPhone 5.5형 (2208 * 1242)
  -  (아이패드에서 동작할 경우) iPad 12.9형 (2732 * 2048) 
- 미리보기 동영상 (optional) 
[참고이미지]
![image](https://user-images.githubusercontent.com/20364535/129551493-6033d23f-75e8-4f4d-8842-8fe896eda1b5.PNG)
### 앱 정보
![image](https://user-images.githubusercontent.com/20364535/129550997-651d1336-1d95-49c9-8e96-6530b213e9d2.png)
- 앱이름
- 부제

- 프로모션 텍스트 : App Store의 앱 설명 위에 표시됩니다.(170자)
- 설명 : 앱의 특징과 기능에 대한 자세한 설명입니다. ( 4,000자)
- 키워드 : 앱을 설명하는 하나 이상의 키워드를 포함하십시오. 키워드를 사용하면 App Store 검색 결과의 정확도를 높일 수 있습니다. 쉼표, 중국어 쉼표 또는 두 쉼표 모두 사용하여 각 키워드를 구분할 수 있습니다. (100자)
- 지원 URL : 앱에 대한 지원 정보가 포함되어 있는 URL입니다
- 마켓팅 URL : 앱에 대한 마케팅 정보가 포함되어 있는 URL
- 개인정보 처리방침 URL : 모든 앱에는 개인정보 처리방식이 필요합니다.
- 저작권 : 앱에 대해 독점 권한을 가진 개인 또는 법인의 이름으로, 앞에 권한을 획득한 연도가 옵니다(예: ‘2008 Acme Inc.’). URL을 제공하지 마십시오.
- 카테고리
- 추가카테고리
![image](https://user-images.githubusercontent.com/20364535/129563473-16d9464d-8248-4dfa-b65f-165ab01c2f5e.png)
![image](https://user-images.githubusercontent.com/20364535/129563523-5be8d6b5-f7d1-4013-9401-2f0305fd64d9.png)

[참고이미지]
![image](https://user-images.githubusercontent.com/20364535/129562418-0d6e0b6a-9c99-4d74-93cf-254240efdb5c.png)

![image](https://user-images.githubusercontent.com/20364535/129562548-92485e21-18ec-4370-81fe-a41dbd18158d.png)

![image](https://user-images.githubusercontent.com/20364535/129563284-92e8f28e-6f54-48f9-b1df-7a82ff261971.png)

**Comment by Jung-Saver** [comment]
준비되면 연락드리겠습니다. 감사합니다.

**Comment by Jung-Saver** [comment]
앱 스크린샷 이미지 최소 2장 최대 10장
iPhone 6.5형 (2778 * 1284)
iPhone 5.5형 (2208 * 1242)
(아이패드에서 동작할 경우) iPad 12.9형 (2732 * 2048)

위와 같이 요청 주셨는데, 저희 아이패드요 디자인도 필요한건가요?

**Comment by ejei0g** [comment]
아이폰 전용앱일 경우에는 아이패드 스크린샷은 넣지 않아도 된다고 합니다. 아이폰 전용 스크린샷만 제공해주시면 됩니다.
[참고]
스크린샷 - iPad를 지원하지 않으면 iPad 스크린샷 생략 가능 (단 Xcode에서 지원기능을 iPhone로만 설정해야 가능)
6.5형 디스플레이: 1242x2688 (주의 - reject사유: iPhone X 이상 단말기가 들어간 이미지를 첨부해야함)
5.5형 디스플레이: 1242x2208 (주의 - reject사유: iPhone 8 이하 단말기만 가능)

<img width="841" alt="Screen Shot 2021-08-20 at 5 40 49 PM" src="https://user-images.githubusercontent.com/20364535/130206202-7f21f433-bc1c-4606-89ea-d987c7bd6185.png">

**Comment by Jung-Saver** [comment]
[스크린샷_iOS용.zip](https://github.com/innovationacademy-kr/slabs-saver/files/7029736/_iOS.zip)

[ios가이드.pdf](https://github.com/innovationacademy-kr/slabs-saver/files/7029745/ios.pdf)

ios 앱 런칭 관련 자료 보내드립니다

**Comment by Jung-Saver** [comment]
안녕하세요? 
 
1,2 은 axios의 경우 모두 웹페이지로 연동되어 있습니다. 
 
3. 스크린샷 또한 아이폰 이미지가 아닌 것으로 등록되어 있어서, 이것이 바뀐 규정인가요?
 
4. 아이패드는 사용하지 않겠습니다. 
 
 
 


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by feldblume5263** [comment]
1번과 2번의 경우에는 페이지를 생성할 때, 들어가게 될 내용을 알려주시면 감사하겠습니다.
    
1번 지원URL 페이지에 따로 추가해야 할 내용이 없으시다면, 고객센터 이메일로 사용하실 이메일 주소를 알려주시면 감사하겠습니다.
    
2번의 개인정보처리방침의 경우에는 다음과 같이 개인정보 처리방침에 대한 내용이 필요합니다.   
<img src="https://user-images.githubusercontent.com/53016167/130420595-c42e88fc-277e-4d16-81a4-6acba90f10f3.jpeg"  width="200" height="400"/>
   
3번의 경우 해당 reject 사유의 경우 바뀐 규정이 아니라 이미 댓글에 적힌 부분을 다시 한번 말씀드린거라... 일단 현재 스크린샷으로 등록 진행을 해보고, 후에 리젝이 되면 그 때 저희가 다시 한번 요청드려도 될 것 같습니다.

**Comment by Jung-Saver** [comment]
[iOS_기기 이미지 변경 (1).zip](https://github.com/innovationacademy-kr/slabs-saver/files/7035815/iOS_.1.zip)
수정된 이미지 먼저 공유드립니다.

**Comment by Jung-Saver** [comment]
1.  문의 이메일 :  saverdevelop@gmail.com
2.  개인정보 보호 :  첨부파일file:///C:/Users/%EA%B9%80%EC%A0%95%EC%84%A0/Downloads/%EC%84%B8%EC%9D%B4%EB%B2%84.html
[세이버.xls](https://github.com/innovationacademy-kr/slabs-saver/files/7036592/default.xls)

**Comment by feldblume5263** [comment]
넵 확인했습니다!! 감사합니다!!ㅎㅎ

**Comment by feldblume5263** [comment]
마지막으로 한 부분에서 수정이 더 필요할 것 같습니다!   
5.5인치는 문제가 없지만,   
6.5인치에서 1284 x **2778** 크기의 파일이어야 하는데, 보내주신 파일의 실제 크기가 1284 x **2278** 파일 크기이기 때문에  1284 x 2778 로 수정이 필요할 것 같습니다.    
저희가 이미지 크기 변경을 시도했으나 이미지가 길게 늘어지는 현상을 해결할 수 없어서 이 부분에서 수정을 부탁드려야 할 것 같습니다.   

보내주신 6.5인치 스크린샷 5장 모두 해당됩니다.

감사합니다.

<img width="400" alt="Screen Shot 2021-08-24 at 2 44 26 PM" src="https://user-images.githubusercontent.com/53016167/130562615-7d40d7f1-e925-410d-9e9c-4fbf52e7c19e.png">

**Comment by Jung-Saver** [comment]
[iOS 6.5형_0824.zip](https://github.com/innovationacademy-kr/slabs-saver/files/7037334/iOS.6.5._0824.zip)
 수정한 파일 다시 드립니다.
