### ISSUE TITLE
[Feature request] cms 오늘의 기사 관리/ 오늘의 한마디 관리 최신순으로 정리

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#429]

**Comment by Jung-Saver** [comment]
이건 아직 수정이 안되었는데, 클로즈 되었습니다
 


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by jis-kim** [comment]
현재 dev에 적용된 상태입니다.

**Comment by jis-kim** [comment]
@Jung-Saver 오늘의 기사, 오늘의 한마디 관리 페이지 기사리스트 수정일 기준으로 변경 되었습니다. 이에 따라 입력일시 항목도 수정일로 표기되도록 변경했습니다.
