### ISSUE TITLE
[Bug report] 접기로 홈에 돌아왔을 때, 해당 기사가 아닌 앞서 포스팅 된 기사로  갑니다. 

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#448]
![KakaoTalk_20210819_162931483_02](https://user-images.githubusercontent.com/84112402/130026896-8b77fc12-5c33-45a5-b082-f1eb58ce7617.jpg)
이 기사를 '더 자세히"버튼을 확장시킨 후
![KakaoTalk_20210819_162931483_01](https://user-images.githubusercontent.com/84112402/130026965-e34dbd41-c97a-469d-a707-b41d7e12f282.jpg)
'접기' 버튼을 누르면
![KakaoTalk_20210819_162931483](https://user-images.githubusercontent.com/84112402/130027029-d03da9da-008e-4ea8-8b5b-e68d899f95d6.jpg)
해당기사가 아닌 2개 앞서 포스팅된 기사 화면으로 이동

**Comment by hokim2407** [comment]
혹시 어느 기종 쓰셨는지 알려주실 수 있나요?

**Comment by Jung-Saver** [comment]
아이폰 8입니다
​
-----Original Message-----
