### ISSUE TITLE
[Feature request]섹션 안내 문구 수정 : 사회/ 문화

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#451]
## 메뉴단의  섹션 소개글 교체 부탁드립니다. 
 
사회 : 우리들 살아가는 세상 이야기
      세이버와 친구처럼 친절하게 알려드립니다. 

문화 : 영화, 음악, 책, 축제…
      세이버가 전하는 문화소식은 새롭습니다. 
![KakaoTalk_20210819_163813210](https://user-images.githubusercontent.com/84112402/130027833-93209c42-6247-42a4-b1ab-2ba5b1722b20.jpg)

**Comment by hokim2407** [comment]
수정되었습니다~
