### ISSUE TITLE
[Feature Request] AM7/PM7 관리자 페이지와 유저 화면 관련 문의

### ISSUE THREAD

**Issue by jis-kim** [innovationacademy-kr/slabs-saver#473]
@Jung-Saver 
안녕하세요.
현재 AMPM이 오전 7시/ 오후 7시에 chief 가 쓴 글으로 자동 생성되는 기능이 적용되었습니다.

## 내용
문의 드리고 싶은 사항은 다음과 같습니다.
1. 관리 페이지
a.현재 홈 - 전체 카테고리에서는 ampm 기사가 나타나지 않고 ampm 카테고리에서는 ampm 기사가 나타나는 상황입니다.
b. chief 계정으로 접속했을 때 내 기사 목록에는 나타납니다.
c. 알림보내기 페이지에는 나타납니다.
d. 오늘의 기사 관리 페이지에는 나타나지 않습니다.

이 중 변경사항이 있으신지 문의드리고 싶습니다.
또한 알림 기능은 글 게재와 동시에 알림을 보내는 기능을 추가할 지, 아니면 그대로 알림보내기 페이지에서 원하는 때에 알림을 보내게 둘 지 변경할 수 있습니다.

2. 사용자 페이지
a. 보내주신 android 샘플 이미지와 현재 ampm 생성되는 기사의 제목 양식이 다른데 샘플 이미지대로 제목을 변경할 수 있습니다.
b. 북마크 및 공유 버튼이 남아있는데 기능을 그대로 둬도 될지 문의드리고 싶습니다.

그 외 변경사항 있으시면 댓글 부탁드립니다.
감사합니다.

**Comment by Jung-Saver** [comment]
문의주신 사안에 아래와 같이 답변드립니다. 

1. 관리 페이지
a.현재 홈 - 전체 카테고리에서는 ampm 기사가 나타나지 않고 ampm 카테고리에서는 ampm 기사가 나타나는 상황입니다.
**- 전체 카테고리에서는 게재된 기사 가운데 am7 또는 pm7에 반영될 기사를 선택하는 페이지로,ampm 기사가 나타지 않는게 맞습니다. 
- am,pm은 '오늘의 기사'처럼 별도 페이지가 존재하고, 거기에서 날짜를 지정하면, 해당일자에  am7 또는 pm7으로 선택된 기사가 별도로 보이서, 편집장이 확인할 수 있었으면 좋겠습니다.** 
b. chief 계정으로 접속했을 때 내 기사 목록에는 나타납니다.
c. 알림보내기 페이지에는 나타납니다.
d. 오늘의 기사 관리 페이지에는 나타나지 않습니다.
**-bcd는 수정 사항 없습니다.** 

이 중 변경사항이 있으신지 문의드리고 싶습니다.

또한 알림 기능은 글 게재와 동시에 알림을 보내는 기능을 추가할 지, 아니면 그대로 알림보내기 페이지에서 원하는 때에 알림을 보내게 둘 지 변경할 수 있습니다.
### - 회원이 'my section'으로 등록한 기사는 게재와 동시에 알림이 나가는 방식이 원칙입니다.
- 개발된 알림 보내기는 개별 기사를 전체 회원에게 보낼 때, 사용 가능한 방식입니다. 감사합니다. 
   아울러, 마케팅 활동을 위한 알림 내용을 작성할 수 있는 기능도 있었으면 합니다. 

사용자 페이지
a. 보내주신 android 샘플 이미지와 현재 ampm 생성되는 기사의 제목 양식이 다른데 샘플 이미지대로 제목을 변경할 수 있습니다.
**- 현재 방식이 더 좋습니다. 그냥 두셔도 됩니다.** 
b. 북마크 및 공유 버튼이 남아있는데 기능을 그대로 둬도 될지 문의드리고 싶습니다.
**- 북마크와 공유 버튼  오른쪽 원 위치에 고정 부탁드립니다** 
그 외 변경사항 있으시면 댓글 부탁드립니다.
감사합니다.

**Comment by jis-kim** [comment]
답변 감사합니다. 해당 답변에 기반해서 기능 추가해보도록 하겠습니다.
