### ISSUE TITLE
[Feature request] 이전 기사 등록 관련 요청사항

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slabs-saver#476]
## 내용
![KakaoTalk_20210820_164246308](https://user-images.githubusercontent.com/84112402/130198610-a1415a27-d2b6-4c8d-a430-579f9fc1d044.jpg)

이전 기사를 불러올때 , 형식이

'1. 봉오동~~~~~' 에서 

' 이전 관련 기사 : 봉오동~~~~" 로 수정해주셨으면 합니다. 

감사합니다.

**Comment by hokim2407** [comment]
요청사항 반영 되었습니다! 
이미 등록된 기사는 일반 링크와 동일한 방식으로 수동으로 이름 변경 해주셔야 합니다.
감사합니다.
