### ISSUE TITLE
[Feature request] ios 앱 등록을 위한 고객센터 페이지 생성(재요청)

### ISSUE THREAD

**Issue by feldblume5263** [innovationacademy-kr/slabs-saver#492]
### 1. 지원 URL에 들어갈 내용이 필요합니다.   
지원URL에는 고객센터 페이지로서, 유저들이 회사와 연락할 방법이 들어가야 합니다.   
```
사용자는 궁금한 점이 생기거나 문제가 발생했을 때 개발자에게 연락할 방법을 알고 있어야 합니다. 
앱과 지원 URL에 개발자에게 연락할 수 있는 손쉬운 방법을 명시해야 합니다. 
이는 수업에 사용되는 앱의 경우 특히 중요합니다. 
정확한 최신 연락처 정보가 없으면 고객의 불만을 유발할 뿐 아니라 일부 국가에서는 법에 저촉될 수 있습니다.
또한 지갑 패스에 발급자의 유효한 연락처 정보가 있는지, 해당 패스의 브랜드 또는 상표 소유자에게 할당된 전용 인증서로 서명되어 있는지 확인하십시오. 
```

**thesaver.io/help url로 지원url 등록 필요
고객센터 페이지 생성을 위한 내용 + 디자인 요청드립니다.**

**Comment by ejei0g** [comment]
![image](https://user-images.githubusercontent.com/20364535/130410394-ead7f5cb-f366-4016-9ee0-21849ade0c94.png)

**Comment by ejei0g** [comment]
![image](https://user-images.githubusercontent.com/20364535/130441000-59c29843-dba8-4e86-9688-9168016103ee.png)
