### ISSUE TITLE
[Feature request] iOS 앱 등록을 위한 약관 페이지 생성

### ISSUE THREAD

**Issue by feldblume5263** [innovationacademy-kr/slabs-saver#493]
### 2. 개인정보 처리방침 URL에 들어갈 내용이 필요합니다.
```
모든 앱에는 App Store Connect 메타데이터 영역과 앱 내부에 쉽게 볼 수 있는 개인정보 처리방침 관련 링크가 포함되어야 합니다.
개인정보 처리방침은 분명하고 명시적으로 다음 요건을 준수해야 합니다.
앱과 서비스가 수집하는 대상 정보(있는 경우), 정보 수집 방법, 수집한 정보의 사용 목적을 정의해야 합니다.
본 지침을 준수하여 앱을 통해 사용자 정보를 공유하는 타사(예: 분석 도구, 광고 네트워크, 타사 SDK, 사용자 정보에 접근할 수 있는 모회사, 
자회사 또는 관련 기관)는 앱의 개인정보 처리방침에 명시되고 본 지침에서 요구하는 것과 동일하거나 동등한 수준으로
사용자 정보 보호를 제공하고 있음을 확인해야 합니다.
정보 보유/삭제 관련 정책을 설명하고, 사용자가 동의를 철회하고 정보 삭제를 요구할 수 있는 방법을 명시해야 합니다.
```
해당 내용은 아마도 다음 절차를 통해 조금 더 간편하게 생성할 수 있습니다.
[개인정보 처리방침 생성 방법](https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=taerg89&logNo=221597544190)
   

**iOS 앱 등록을 위한 약관 페이지(개인정보 처리방침 URL) 
thesaver.io/policy
약관 페이지 생성을 위한 내용 + 디자인 요청드립니다.**

**Comment by ejei0g** [comment]
![image](https://user-images.githubusercontent.com/20364535/130410503-c2a70fb8-7a00-49db-a093-bf78384fa966.png)

**Comment by Jung-Saver** [comment]
작성 후 공유 드리겠습니다.

**Comment by Jung-Saver** [comment]
https://docs.google.com/document/d/19teEbJWEPjjPPKTcr3XrYxTlzYGKWejvCPTFMWRMXUw/edit

[세이버 서비스 이용약관_210824.pdf](https://github.com/innovationacademy-kr/slabs-saver/files/7037571/_210824.pdf)

약관 전달 드립니다.
