### ISSUE TITLE
[Feature request] Android 앱 등록을 위한 서명정보 요청

### ISSUE THREAD

**Issue by parkjh2568** [innovationacademy-kr/slabs-saver#498]
## 내용
![image](https://user-images.githubusercontent.com/62925498/130424551-8565251c-e3a4-4618-889e-f3bfb5aef75e.png)

앱에 서명으로 등록될 key파일의 세부데이터를 위와같이 진행을 해도 될까요?? 

![image](https://user-images.githubusercontent.com/62925498/130433114-6dde4186-6a90-4621-98af-51ecf7ac03b5.png)

추가로 키의 이름과 비밀번호도 기존에 쓰던것으로 적용하고 내역을 전달할지
혹은 원하시는것 이름과 비밀번호가 있으시면 알려주세요

**Comment by kenu** [comment]
서명 위 정보대로 진행해주세요.
